
---
title: "MARS_on_sample"
output:
  html_document:
    toc: true
---


```{r}
%md
# Load the data and libraries
```


```{r}
install.packages('hexbin')
install.packages('earth')
```


```{r}
library(tidyverse)
library(hexbin)
library(caret)
library(earth)
library(RColorBrewer)
```


```{r}
df = read.csv("/dbfs/FileStore/tables/df1_sample.csv")
```


```{r}
colnames(df)
```


```{r}
bin <- hexbin( db$day_of_year, db$SPEED)
 
plot(bin, main="" , colramp=colorRampPalette(c("grey", "green")) ,
     legend=F )
```


```{r}
# Filtering data to remove rows where 0 > SPEED > 68
db = subset ( df, SPEED > 0 )
db = subset ( db, SPEED < 68 )
```


```{r}
%md
# Multivariate Adaptive Regression Splines
```


```{r}
set.seed(69)
```


```{r}
bin <- hexbin(db$hour, db$SPEED)
 
plot(bin, main="" , colramp=colorRampPalette(c("grey", "green")) ,
     legend=F )
```


```{r}
db %>%
  ggplot(aes(x = hour, y = SPEED) ) +
  geom_point() +
  geom_smooth(method='lm', fill = 'red') +
  geom_smooth(fill = 'green')
```


```{r}
# Sampling the data
train_indices <- sample(1:nrow(db), size = floor(0.75 * nrow(db)), replace = FALSE)
train_set <- db[train_indices,]
test_set <- db[-train_indices,]

# Defining x and y values
x <- train_set[, 6:12]
y <- train_set[, 2]

# Pruning Grid
parameter_grid <- floor(expand.grid(degree = 1:4, nprune = seq(5, 50, by = 5)))


# training the models, whilst performing cross validation
cv_model <- train(x = x,
                  y = y,
                  method = "earth",
                  metric = "RMSE",
                  trControl = trainControl(method = "cv", number = 10),
                  tuneGrid = parameter_grid)

# Model Information
summary(cv_model$finalModel)
```


```{r}
ggplot(cv_model)
```


```{r}
summary(cv_model$finalModel)
```


```{r}
%md
## Testing the model
```


```{r}
mars_predict <- predict(object = cv_model$finalModel, 
                        newdata = test_set)
```


```{r}
# Get the SSE 
mars_sse <- sum((test_set$SPEED - mars_predict)^2)

# Get the MAE (mean absolute error)
mars_mae <- mean(abs(test_set$SPEED - mars_predict))
```


```{r}
print(c("SSE is",mars_sse))
print(c("MAE is",mars_mae))
```


```{r}
plot(test_set$SPEED,mars_predict)
```


```{r}
plot(test_set$SPEED - mars_predict, 
     main = "Residuals for MARS model", 
     xlab = "Observation number in test set", 
     ylab = "Residual")
```


```{r}
?earth
```


```{r}
%md
# Model 2: Adaptive Spline Model
```


```{r}
model2 <- earth(formula = SPEED~day_of_year, data = db)
```


```{r}
summary(model2)
```

